name: iOS CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: macos-15 
    
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 16,OS=18.0']
    
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.2.2
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.6.0
      with:
        xcode-version: '16.2'

    - name: Build and test
      run: |
        set -o pipefail
        xcodebuild test \
          -scheme MixpanelSwiftCommon \
          -destination "${{ matrix.destination }}" \
          -enableCodeCoverage YES \
          -derivedDataPath Build/ \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO | xcpretty